### ISSUE TITLE
配置

### ISSUE THREAD

**Issue by dmdoit** [davidroyer/vue2editor-images#4]
```
dynamic:
  druid: #以下是全局默认值，可以全局更改
    validation-query-timeout: 2000
    initial-size: 5
    max-active: 20
    min-idle: 5
    max-wait: 60000
```
